### ISSUE TITLE
TPDTC and TPRTC types sharing

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.SDK#184]
@dsyme 
I tried TPDTC/TPRTC separation for NET Standard 2.0 but it failed.
How do I refer to types in TPRTC from TPDTC?
I know old way was 
https://github.com/fsprojects/FSharp.Management/blob/master/src/FSharp.Management.WMI.DesignTime/WmiProvider.DesignTime.fs#L20

I saw in examples 
https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/3438c4817b4e25884169ee7be6182efa39995057/examples/BasicProvider.DesignTime/BasicProvider.DesignTime.fsproj#L9
and
https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/3438c4817b4e25884169ee7be6182efa39995057/examples/BasicProvider.DesignTime/BasicProvider.Provider.fs#L18

I tried but it doesn't work. When I add reference to TPRTC in consumption projects it complains about shared types missing from TPDTC. 
Is there re-write process that substitute  shared types TPDTC ->  TPRTC ?
```ConvertSourceTypeToTarget``` seems to be invoked only for generative providers.
https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/3438c4817b4e25884169ee7be6182efa39995057/src/ProvidedTypes.fs#L8885

**Comment by dsyme** [comment]
@dmitry-a-morozov I believe you must specify an assemblyReplacementMap in this case, see examples
* https://github.com/fsharp/FSharp.Data/blob/90e8dc8c3ffddd3b3279193e202d87d2f6c6db2e/src/Html/HtmlProvider.fs#L18
* https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/examples/BasicProvider.DesignTime/BasicProvider.Provider.fs#L12

> ConvertSourceTypeToTarget seems to be invoked only for generative providers.

``convTypeToTgt`` is called in a lot of places, including for erased providers

**Comment by dmitry-a-morozov** [comment]
Thanks. That worked. 
I got interesting case where I have enumeration type that used in type provider input static params and runtime.
Types replacement doesn't touch static parameters, right?
So I pulled this one enum in old-fashion way via ```config.RuntimeAssembly```
https://github.com/fsprojects/FSharp.Management/blob/master/src/FSharp.Management.WMI.DesignTime/WmiProvider.DesignTime.fs#L20

**Comment by dsyme** [comment]
> Types replacement doesn't touch static parameters, right?

I had assumed it didn't have to: static parameter types are specified by the TP author in terms of source types, but I suppose the F# compiler needs those as target types in the case of enums (I believe the value for an enum-typed static parameter is given back to the TP as an integer, so that's not the issue)

I will add a  bug about that.

**Comment by dsyme** [comment]
@dmitry-a-morozov OK, #188 is fixed, you shouldn't need to use config.RuntimeAssembly any more

**Comment by dmitry-a-morozov** [comment]
@dsyme Thank you.

**Comment by dmitry-a-morozov** [comment]
@dsyme After reviewing my code I realized that it's bad idea to have design-time types leaking into run-time. Be sure that you didn't add this feature only to support mistake in my design.

**Comment by dmitry-a-morozov** [comment]
@dsyme Bizarre thing is that it works when I test with local assembly but fails when nuget package is used.
I don't understand how that is possible. 
Compiler still looks for design time type when dependency brought via nuget.

**Comment by sergey-tihon** [comment]
> Compiler still looks for design time type when dependency brought via nuget.
How VS behave in this case?

I am asking because we do have the strange bug in SwaggerProvider and have to idea what is wrong, and it appears only when TP restored from NuGet (all your tests are green).
- user reference TS NuGet package
- type `type myTP = SwaggerProvider<...>`
- after a couple of seconds, intelligence appear for provided type
- sometime later (30sec in my case) when I start using intelligence over provided method - everything break and TP shows error `Incorrect instance type Parameter name: obj`
- video is here - https://github.com/fsprojects/SwaggerProvider/issues/101#issuecomment-364036061

P.S. Just checking if it is TPSDK related and should I open new issuer here or not...

**Comment by dmitry-a-morozov** [comment]
@sergey-tihon Yes I see really weird and inconsistent errors :(.
